language: node_js
node_js: stable

cache:
  directories:
    - node_modules

before_install:
  - export TZ='Asia/Shanghai'

install:
  - npm install

script:
  - npm run build:ts
  - npm run build "${GITHUB_SNIPPET}"
  - npm run build:snippets

after_script:
  - cd ./dist
  - git init
  - git config user.name "BiYuqi"
  - git config user.email "biyuqiwan@163.com"
  - git add README.md
  - git commit -m "Travis CI Auto Generate at `date +"%Y-%m-%d %H:%M"`"
  - git push --force --quiet "https://${GITHUB_SNIPPET}@${GH_REF}" master:master
  - git add index.html snippets.js
  - git commit -m "Travis CI Auto Generate at `date +"%Y-%m-%d %H:%M"`"
  - git push --force --quiet "https://${GITHUB_SNIPPET}@${GH_REF}" master:gh-pages

branches:
  only:
    - issue-typescript
env:
 global:
   - GH_REF: github.com/BiYuqi/snippets.git