language: node_js
node_js: stable

cache:
  directories:
    - node_modules

before_install:
  - export TZ='Asia/Shanghai'

install:
  - npm install

script:
  - npm run build "${GITHUB_SNIPPET}"

after_script:
  - cd ./dist
  - git init
  - git config user.name "BiYuqi"
  - git config user.email "biyuqiwan@163.com"
  - git add .
  - git commit -m "Travis CI Auto Generate at `date +"%Y-%m-%d %H:%M"`"
  - git push --force --quiet "https://${GITHUB_SNIPPET}@${GH_REF}" master:master

branches:
  only:
    - issue-branch
env:
 global:
   - GH_REF: github.com/BiYuqi/snippets.git