name: Auto Generate Issue Blog

on: [issues, issue_comment, label, push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v1

    - name: Use Node.js 10.x
      uses: actions/setup-node@v1
      with:
        node-version: "10.x"

    - name: Setup Global Env
      env:
        GITHUB_LOGIN: BiYuqi
        GITHUB_REPO: snippets
      run: |
        git config --global user.email "biyuqiwan@163.com"
        git config --global user.name "BiYuqi"
    - name: Install
      env:
        GITHUB_LOGIN: BiYuqi
        GITHUB_REPO: snippets
      run: |
        npm install
        npm run build
    - name: commit change
      run: |
        git add .
        git commit -m "Update from Github Action"
    - name: push change
      env:
        GITHUB_LOGIN: BiYuqi
        GITHUB_REPO: snippets
        GITHUB_TOKEN: 07413d81b67fcb2ccb0376044c9d52f9640863d8
      run: |
        git push https://$GITHUB_LOGIN:$GITHUB_TOKEN@github.com/$GITHUB_REPO.git
    - name: done
      run: echo 'done'
